### PR TITLE
Catch IllegalFormatConversionException and throw with more info

### LINKED ISSUE #1: Could throw a more helpful error on IllegalFormatConversionException
I currently wrap named-format like so:

```
(defn named-format
  [format-str arg-map & [other-info]]
  (try
    (named-format/named-format format-str arg-map)
    (catch java.util.IllegalFormatConversionException e
      (throw (ex-info "Unable to use named-format!" {:format-str format-str
                                                     :arg-map    arg-map
                                                     :other-info other-info})))))

```

The "other info" is helpful for me figuring out exactly which part of my data is causing the problem, but probably wouldn't be useful for everyone. It is helpful to have :format-str and :arg-map always though.

I don't know, any thoughts?

### PR DESCRIPTION
**Pull request by WhittlesJr**
Resolves #1 

Well, here's an attempt... the inlining makes things very messy. I stared at this for a while wondering if defining the function outside of the macro would ruin the inline optimization or not. I'm still not sure and it was hurting my brain so I decided to just hand this over as is. 

Does this work? Do I actually have to re-implement throw-on-bad-format in three places? If so, why?

### CODE REVIEW

File: src/com/gfredericks/like_format_but_with_named_args.clj [hunk 1]
```diff
@@ -22,6 +22,13 @@
                      remaining)
               (throw (ex-info "Bad format string!" {:arg format-str})))))))))
 
+(defn throw-on-bad-format
+  [format-string arg-map e]
+
+  (throw (ex-info "Unable to use named-format!" {:format-string format-string
+                                                 :arg-map       arg-map
+                                                 :cause         (.getMessage e)})))
```
Comment (gfredericks) [inline src/com/gfredericks/like_format_but_with_named_args.clj]: the cause can be passed as the third arg to `ex-info`

File: src/com/gfredericks/like_format_but_with_named_args.clj [hunk 2]
```diff
@@ -22,6 +22,13 @@
                      remaining)
               (throw (ex-info "Bad format string!" {:arg format-str})))))))))
 
+(defn throw-on-bad-format
+  [format-string arg-map e]
+
+  (throw (ex-info "Unable to use named-format!" {:format-string format-string
```
Comment (gfredericks) [inline src/com/gfredericks/like_format_but_with_named_args.clj]: How about a message like "Bad call to named-format"

File: src/com/gfredericks/like_format_but_with_named_args.clj [hunk 3]
```diff
@@ -46,11 +53,17 @@
                    ;; "%%" -> "%" conversion.
                    (format clojure-format-string)
                    `(let [arg-map# ~arg-map]
-                      (apply format ~clojure-format-string (map #(get arg-map# %) ~names)))))
+                      (try (apply format ~clojure-format-string (map #(get arg-map# %) ~names))
+                           (catch java.util.IllegalFormatConversionException e#
+                             (throw-on-bad-format ~clojure-format-string arg-map# e#))))))
```
Comment (gfredericks) [inline src/com/gfredericks/like_format_but_with_named_args.clj]: unquoting `clojure-format-string` a second time here has the slight drawback that the string literal will be compiled into the code twice; this can be avoided by unquoting it once in the `let` form on line 48/55: `clojure-format-string# ~clojure-format-string`, the same way as `arg-map`.

**Review by gfredericks — CHANGES_REQUESTED** [review]
Looks good, just a few minor changes. Thanks!

**Comment by WhittlesJr** [comment]
How's that?

File: src/com/gfredericks/like_format_but_with_named_args.clj [hunk 4]
```diff
@@ -25,9 +25,9 @@
 (defn throw-on-bad-format
   [format-string arg-map e]
 
-  (throw (ex-info "Unable to use named-format!" {:format-string format-string
-                                                 :arg-map       arg-map
-                                                 :cause         (.getMessage e)})))
+  (throw (ex-info "Bad call to named-format" {:format-string format-string
+                                              :arg-map    arg-map}
+                  (.getMessage e))))
```
Comment (gfredericks) [inline src/com/gfredericks/like_format_but_with_named_args.clj]: this should be just `e`, not `(.getMessage e)` -- the jvm `Throwable` class has a mechanism for attaching one exception to another (see [here](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#getCause--)); in fact, I think the code as you have it will break, so I'm interested in whether there's a test that is failing.

**Review by gfredericks — CHANGES_REQUESTED** [review]

File: src/com/gfredericks/like_format_but_with_named_args.clj (hunk 4 above)
Comment (WhittlesJr) [reply src/com/gfredericks/like_format_but_with_named_args.clj]: Woof, sorry. That was sloppy of me.

**Comment by gfredericks** [comment]
Thanks, released as `0.1.4`
